"use client";

import { useState } from "react";
import { UploadCloud, FileText, Activity, AlertCircle, Loader2 } from "lucide-react";
import { motion } from "framer-motion";

export default function PatientRecords() {
  const [file, setFile] = useState<File | null>(null);
  const [isUploading, setIsUploading] = useState(false);
  const [analysis, setAnalysis] = useState<string | null>(null);

  const handleUpload = async () => {
    if (!file) return;
    setIsUploading(true);

    try {
      const formData = new FormData();
      formData.append("file", file);

      // Step 1: Upload to server for OCR
      const ocrRes = await fetch("/api/ocr", { method: "POST", body: formData });
      const ocrData = await ocrRes.json();

      if (ocrData.text) {
        // Step 2: Send text to AI for analysis
        const aiRes = await fetch("/api/ai/analyze", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ text: ocrData.text, type: "report" }),
        });
        const aiData = await aiRes.json();
        setAnalysis(aiData.result);
        
        // Note: Real application would also upload file to Cloudinary and save record in Convex here
      }
    } catch (error) {
      console.error("Failed to analyze report", error);
    } finally {
      setIsUploading(false);
    }
  };

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Medical Records</h1>
        <p className="text-gray-500 mt-2">Upload your lab reports to get AI-powered insights.</p>
      </div>

      <div className="bg-white dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 rounded-3xl p-8 shadow-sm">
        <div className="flex flex-col items-center justify-center border-2 border-dashed border-teal-200 dark:border-teal-900/50 rounded-2xl p-12 bg-teal-50 dark:bg-teal-900/10">
          <UploadCloud className="w-16 h-16 text-teal-500 mb-4" />
          <h3 className="text-lg font-bold mb-2">Upload Lab Report</h3>
          <p className="text-gray-500 text-sm mb-6 text-center max-w-sm">
            Drag and drop your PDF or image here, or click to browse. Our AI will automatically extract and analyze the data.
          </p>
          
          <input 
            type="file" 
            id="report-upload" 
            className="hidden" 
            accept="image/*,.pdf"
            onChange={(e) => setFile(e.target.files?.[0] || null)}
          />
          <label 
            htmlFor="report-upload" 
            className="bg-teal-600 hover:bg-teal-700 text-white px-6 py-3 rounded-xl font-medium cursor-pointer transition"
          >
            Select File
          </label>
          {file && <p className="mt-4 text-teal-600 font-medium text-sm flex items-center gap-2"><FileText className="w-4 h-4"/> {file.name}</p>}
        </div>

        <div className="mt-6 flex justify-end">
          <button 
            onClick={handleUpload}
            disabled={!file || isUploading}
            className="bg-gray-900 dark:bg-white text-white dark:text-gray-900 px-8 py-3 rounded-xl font-bold disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
          >
            {isUploading ? <><Loader2 className="w-5 h-5 animate-spin" /> Analyzing...</> : "Analyze Report"}
          </button>
        </div>
      </div>

      {analysis && (
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="bg-white dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 rounded-3xl p-8 shadow-sm relative overflow-hidden">
          <div className="absolute top-0 right-0 p-4">
            <Activity className="w-24 h-24 text-teal-500/10" />
          </div>
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 bg-teal-100 dark:bg-teal-900/30 text-teal-600 rounded-xl flex items-center justify-center">
              <Activity className="w-5 h-5" />
            </div>
            <h2 className="text-xl font-bold">AI Analysis Result</h2>
          </div>
          <div className="prose dark:prose-invert max-w-none text-gray-700 dark:text-gray-300">
            {analysis.split("\n").map((line, i) => (
              <p key={i}>{line}</p>
            ))}
          </div>
          
          <div className="mt-8 bg-orange-50 dark:bg-orange-900/20 border border-orange-200 dark:border-orange-800/50 p-4 rounded-xl flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-orange-600 dark:text-orange-400 shrink-0 mt-0.5" />
            <p className="text-sm text-orange-800 dark:text-orange-200">
              <strong>Medical Disclaimer:</strong> This analysis is generated by Artificial Intelligence based on the extracted text. It may contain errors and is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician.
            </p>
          </div>
        </motion.div>
      )}
    </div>
  );
}
